### PR TITLE
Major GitHub/GraphQL Update

### PR DESCRIPTION
**Pull request by LRWeber**
All new code for user-friendly handling of GraphQL and REST queries to GitHub.

### CODE REVIEW

**Comment by LRWeber** [comment]
@IanLee1521 
There may be some additional re-naming/re-structuring that is required/desired to best incorporate this module. Please let me know your thoughts.

I've also worked on converting our llnl.github.io explore scripts to use this new code (it helped to test a lot more). They should be ready, depending on how we would incorporate this code for usage in that project.

**Comment by LRWeber** [comment]
Unfortunately, subprocess provides more detailed control/functionality that I've been utilizing.
Using `check_output` was specifically helpful because it raises a Python error if the subprocess returns a non-zero exit status.

Using `scraper.util.execute` strips away additional options. It looks like it uses subprocess as well, in a more raw fashion. It's just set to override the security warnings.

I took some cues from the utility script however, and pared-down what actually gets imported from subprocess.

**Comment by LRWeber** [comment]
I've also been wondering, should we update the "requirements" lists at all? For instance, we added "pytz" in our llnl.github.io requirements, and that's still in use here. I believe that should be the only odd additional package.

**Comment by IanLee1521** [comment]
Yes, if we explicitly use it, we should include it.

**Comment by IanLee1521** [comment]
Thanks @LRWeber !

**Pull request merged**
