### PR TITLE
test tweaking github-py to >=2.0.0 for python 3.9 support

### LINKED ISSUE #59: github-py pinned version won't work for newer python
The pin here:

https://github.com/LLNL/scraper/blob/471e06df3c2547b181974b50000dbe32dd86cf54/requirements/production.txt#L1

Means that running in default Python for ubuntu:22.04, we hit this error:

```bash
ImportError: cannot import name 'Callable' from 'collections'
```
triggered in the github3 module. The version here (1.2.0) seems a bit old because latest is 3.2.0 https://pypi.org/project/github3.py/. 

The bug was actually fixed two years ago:

image

so likely if you had a reason to not want to update to latest you could try an older one, [here is the commit](https://github.com/sigmavirus24/github3.py/commit/e67fa14022cea18a937b4605be0a8dd1a73083fd) and the release after that is version 2.0.0. https://pypi.org/project/github3.py/2.0.0/.

Thank you! This broke the automated data parsing for the radius interface, so it would be good to fix soon.  It looks like you have CI setup so I'll take a shot at tweaking this and we can go from there. Thank you!

### PR DESCRIPTION
**Pull request by vsoch**
An import of Callable from collections (instead of collections.abc) in the pinned version means that it breaks with newer Python. Thus we should try to support github3 >= 2.0.0 when this was fixed. This is a test PR to see how dire this change is I am anticipating it will break for older Python versions in which case we should have a discussion about how to properly address this!) It could just be that we move forward supporting newer Python versions and add a note to the README for older versions to use an older version of the library.

I'm not sure why tests aren't triggering but I'm guessing it's because either I need approval (somewhere I can't see that is not here) or .travis.ci is since disconnected because it sort of has died in the last few years. Let me know if you'd like a new testing setup I'd be happy to do that. :)

This will fix #59 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
@IanLee1521 not sure why tests aren't running here (perhaps GH-actions are disabled) but I opened a PR to my branch to show working: https://github.com/researchapps/scraper/actions/runs/2472598848. I also ran the version here against the (currently broken but with the patch here fixed!) contributor-ci action: https://github.com/vsoch/contributor-ci/runs/6824670095?check_suite_focus=true. Works! So I think it would be great to have a release soon, and of course let me know if you want more work here.

**Comment by vsoch** [comment]
thank you!

**Comment by vsoch** [comment]
@IanLee1521 what is the schedule / protocol for new releases?

**Comment by IanLee1521** [comment]
Basically just when I feel like it.

I was trying to test installing in a pipenv, and having trouble, but as soon as I confirm a couple simple cases, I can push out the release.

**Comment by vsoch** [comment]
okay sounds good! Can you post here when you do? And no rush, I put in a custom branch fix a few weeks ago, so I can update this in my tooling whenever is good for you.

**Comment by IanLee1521** [comment]
@vsoch - Sorry for the delay! This is now uploaded to: https://pypi.org/project/llnl-scraper/0.11.0/

Hopefully we didn't break anything along the way 🙃

**Comment by vsoch** [comment]
Thank you!!

**Pull request merged**
